version: '3.1'

services: 
  taxo-postgresql:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: taxo
      POSTGRES_USER: taxo
      POSTGRES_HOST_AUTH_METHOD: "trust"

    networks:
      - taxo-app-network
  taxo-mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - taxo-app-network

networks:
  taxo-app-network:
    driver: bridge
